# Generated by Django 4.0.6 on 2022-07-05 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-date_employed',), 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='team',
            name='date_employed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
